# Define the path of the packages
DF_DK: "dataset_notes/clin_note_danish_df.tsv"

# Define the paths of the model and the model's tokenizer
TOKENIZER: "llama3_1/Meta-Llama-3.1-8B-Instruct/tokenizer.model"
LLM_MODEL: "llama3_1/Meta-Llama-3.1-8B-Instruct/consolidated.00.pth"
PARAMS: "llama3_1/Meta-Llama-3.1-8B-Instruct/params.json"

# Define the special token and the masked probability 
MASK_TOKEN: "[MASK]"
MASK_PROB: 0.15
MASK_TOKEN_ID: 220
